#!/usr/bin/env bash
# memory-bridge-claude — Claude Code SessionEnd hook (bundled plugin).
#
# Flattens this project's Claude Code memory
#   <cc-data-dir>/projects/<slug>/memory/*.md
# into
#   <project>/.opencode/from-claude.md
# the file OpenCode attaches via opencode.json "instructions".
#
# Echo guard: the note that came *from* OpenCode (from-opencode.md) is skipped,
# so OpenCode's own note is never sent back to it. One writer per file => no
# clobber. Design: _reference/hook-sync-research.md §6.
#
# SessionEnd is non-blocking: the exit code cannot affect the session, so we
# always exit 0. Diagnostics go to stderr (visible under `claude --debug` and
# in the hook trace) — these stderr lines are the author's observation points.

# SessionEnd delivers a JSON payload on stdin. Read it only when stdin is a
# pipe, so the script is still safe to dry-run by hand from a terminal.
payload=""
[ -t 0 ] || payload="$(cat)"

end_reason="$(printf '%s' "$payload" | jq -r '.end_reason // "?"' 2>/dev/null || echo '?')"

# Project directory: env var the harness sets -> stdin .cwd -> $PWD (hand-run).
proj="${CLAUDE_PROJECT_DIR:-}"; src="CLAUDE_PROJECT_DIR"
if [ -z "$proj" ] && [ -n "$payload" ]; then
  proj="$(printf '%s' "$payload" | jq -r '.cwd // empty' 2>/dev/null)"; src="stdin.cwd"
fi
[ -n "$proj" ] || { proj="$PWD"; src="PWD"; }

# CC data directory: handles relocated/non-standard installs.
# Priority: CLAUDE_CONFIG_DIR (how production users relocate ~/.claude; the hook
# subprocess inherits it) > CLAUDE_HOME (generic escape hatch, e.g. dev forks)
# > walk up from this script's own path > probe ~/.claude, then ~/.claude-fork.
# BASH_SOURCE[0] is always the real script path — no env var dependency.
# Script lives at <cc-data-dir>/plugins/cache/.../<name>/<ver>/scripts/memory-bridge.sh
# Walk up until we find a dir with both projects/ and plugins/ = CC data dir.
if [ -n "${CLAUDE_CONFIG_DIR:-}" ]; then
  cc_home="$CLAUDE_CONFIG_DIR"; ch_src="CLAUDE_CONFIG_DIR"
elif [ -n "${CLAUDE_HOME:-}" ]; then
  cc_home="$CLAUDE_HOME"; ch_src="CLAUDE_HOME"
else
  # Walk up from script's own path (works when installed into CC plugin cache).
  _dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  cc_home=""
  while [ "$_dir" != "/" ] && [ "$_dir" != "$HOME" ]; do
    if [ -d "$_dir/projects" ] && [ -d "$_dir/plugins" ]; then
      cc_home="$_dir"; ch_src="script-path(walk)"; break
    fi
    _dir="$(dirname "$_dir")"
  done
  # Fallback: probe known CC data dirs in preference order.
  # Covers local-source installs where walk-up stays inside the workspace.
  if [ -z "$cc_home" ]; then
    for _fb in "$HOME/.claude" "$HOME/.claude-fork"; do
      [ -d "$_fb/plugins" ] && { cc_home="$_fb"; ch_src="fallback-probe"; break; }
    done
  fi
  [ -n "$cc_home" ] || { cc_home="$HOME/.claude"; ch_src="default"; }
fi

# CC memory slug = absolute project path, every non-alphanumeric char -> '-'.
slug="$(printf '%s' "$proj" | tr -c '[:alnum:]' '-')"
mem="$cc_home/projects/$slug/memory"
out="$proj/.opencode/from-claude.md"

echo "[memory-bridge-claude] end_reason=$end_reason proj=$proj (via $src)" >&2
echo "[memory-bridge-claude] cc_home=$cc_home (via $ch_src) slug=$slug" >&2

if [ ! -d "$mem" ]; then
  echo "[memory-bridge-claude] no memory dir at $mem -> nothing to sync" >&2
  exit 0
fi

mkdir -p "$(dirname "$out")"
{
  echo "<!-- Auto-generated by Claude Code's SessionEnd hook (memory-bridge-claude)."
  echo "     Source: $mem  —  do not edit by hand; overwritten each session. -->"
  echo
  for f in "$mem"/*.md; do
    [ -e "$f" ] || continue                                  # empty-glob guard
    [ "$(basename "$f")" = "MEMORY.md" ] && continue            # skip CC-internal index
    [ "$(basename "$f")" = "from-opencode.md" ] && continue   # echo guard: skip OpenCode's note
    cat "$f"
    echo
  done
} > "$out"

# Plan B pointer — OC plugin reads this to know the exact CC memory dir, avoiding slug guesswork.
printf '%s\n' "$mem" > "$proj/.opencode/.cc-memory-path"

echo "[memory-bridge-claude] wrote $out" >&2
echo "[memory-bridge-claude] wrote .cc-memory-path -> $mem" >&2
exit 0
